In [53]:
import pandas as pd

In [54]:
data = pd.read_csv('data/training.csv')

In [55]:
data.isna().sum().sum()

np.int64(0)

U datasetu nema null vrednosti.

In [56]:
data.select_dtypes(include='str')

          PIDN    Depth
0     XNhoFZW5  Topsoil
1     9XNspFTd  Subsoil
2     WDId41qG  Topsoil
3     JrrJf1mN  Subsoil
4     ZoIitegA  Topsoil
...        ...      ...
1152  bdcNNrbi  Topsoil
1153  6HBVKZwh  Subsoil
1154  5eLY5nw7  Topsoil
1155  gsSGXhX6  Subsoil
1156  A6IpBbfZ  Topsoil

[1157 rows x 2 columns]

Izbacujemo PDIN koji predstavlja identifikator uzorka

In [57]:
data.drop('PIDN', inplace=True, axis=1)

Pretvaramo Depth obelezje u numericke vrednosti

In [58]:
data['Depth'] = data['Depth'].replace({'Topsoil' : 0 , 'Subsoil' : 1})

## Provera korelacija

In [59]:
import numpy as np

cor_mat = data.corr()
cor_mat_ut = cor_mat.where(np.triu(np.ones(cor_mat.shape), k=1).astype(np.bool))
cols = cor_mat_ut.columns
correlated_columns = []
for column in cols:
    if any(cor_mat_ut[column] > 0.95):
        correlated_columns.append(column)
correlated_columns

['m7496.04',
 'm7494.11',
 'm7492.18',
 'm7490.25',
 'm7488.32',
 'm7486.39',
 'm7484.46',
 'm7482.54',
 'm7480.61',
 'm7478.68',
 'm7476.75',
 'm7474.82',
 'm7472.89',
 'm7470.97',
 'm7469.04',
 'm7467.11',
 'm7465.18',
 'm7463.25',
 'm7461.32',
 'm7459.39',
 'm7457.47',
 'm7455.54',
 'm7453.61',
 'm7451.68',
 'm7449.75',
 'm7447.82',
 'm7445.89',
 'm7443.97',
 'm7442.04',
 'm7440.11',
 'm7438.18',
 'm7436.25',
 'm7434.32',
 'm7432.4',
 'm7430.47',
 'm7428.54',
 'm7426.61',
 'm7424.68',
 'm7422.75',
 'm7420.82',
 'm7418.9',
 'm7416.97',
 'm7415.04',
 'm7413.11',
 'm7411.18',
 'm7409.25',
 'm7407.33',
 'm7405.4',
 'm7403.47',
 'm7401.54',
 'm7399.61',
 'm7397.68',
 'm7395.75',
 'm7393.83',
 'm7391.9',
 'm7389.97',
 'm7388.04',
 'm7386.11',
 'm7384.18',
 'm7382.25',
 'm7380.33',
 'm7378.4',
 'm7376.47',
 'm7374.54',
 'm7372.61',
 'm7370.68',
 'm7368.76',
 'm7366.83',
 'm7364.9',
 'm7362.97',
 'm7361.04',
 'm7359.11',
 'm7357.18',
 'm7355.26',
 'm7353.33',
 'm7351.4',
 'm7349.47',
 'm7347.54',
 'm7345.61',
 'm7343.68',
 'm7341.76',
 'm7339.83',
 'm7337.9',
 'm7335.97',
 'm7334.04',
 'm7332.11',
 'm7330.19',
 'm7328.26',
 'm7326.33',
 'm7324.4',
 'm7322.47',
 'm7320.54',
 'm7318.61',
 'm7316.69',
 'm7314.76',
 'm7312.83',
 'm7310.9',
 'm7308.97',
 'm7307.04',
 'm7305.12',
 'm7303.19',
 'm7301.26',
 'm7299.33',
 'm7297.4',
 'm7295.47',
 'm7293.54',
 'm7291.62',
 'm7289.69',
 'm7287.76',
 'm7285.83',
 'm7283.9',
 'm7281.97',
 'm7280.04',
 'm7278.12',
 'm7276.19',
 'm7274.26',
 'm7272.33',
 'm7270.4',
 'm7268.47',
 'm7266.55',
 'm7264.62',
 'm7262.69',
 'm7260.76',
 'm7258.83',
 'm7256.9',
 'm7254.97',
 'm7253.05',
 'm7251.12',
 'm7249.19',
 'm7247.26',
 'm7245.33',
 'm7243.4',
 'm7241.48',
 'm7239.55',
 'm7237.62',
 'm7235.69',
 'm7233.76',
 'm7231.83',
 'm7229.9',
 'm7227.98',
 'm7226.05',
 'm7224.12',
 'm7222.19',
 'm7220.26',
 'm7218.33',
 'm7216.4',
 'm7214.48',
 'm7212.55',
 'm7210.62',
 'm7208.69',
 'm7206.76',
 'm7204.83',
 'm7202.91',
 'm7200.98',
 'm7199.05',
 'm7197.12',
 'm7195.19',
 'm7193.26',
 'm7191.33',
 'm7189.41',
 'm7187.48',
 'm7185.55',
 'm7183.62',
 'm7181.69',
 'm7179.76',
 'm7177.83',
 'm7175.91',
 'm7173.98',
 'm7172.05',
 'm7170.12',
 'm7168.19',
 'm7166.26',
 'm7164.34',
 'm7162.41',
 'm7160.48',
 'm7158.55',
 'm7156.62',
 'm7154.69',
 'm7152.76',
 'm7150.84',
 'm7148.91',
 'm7146.98',
 'm7145.05',
 'm7143.12',
 'm7141.19',
 'm7139.27',
 'm7137.34',
 'm7135.41',
 'm7133.48',
 'm7131.55',
 'm7129.62',
 'm7127.69',
 'm7125.77',
 'm7123.84',
 'm7121.91',
 'm7119.98',
 'm7118.05',
 'm7116.12',
 'm7114.19',
 'm7112.27',
 'm7110.34',
 'm7108.41',
 'm7106.48',
 'm7104.55',
 'm7102.62',
 'm7100.7',
 'm7098.77',
 'm7096.84',
 'm7094.91',
 'm7092.98',
 'm7091.05',
 'm7089.12',
 'm7087.2',
 'm7085.27',
 'm7083.34',
 'm7081.41',
 'm7079.48',
 'm7077.55',
 'm7075.62',
 'm7073.7',
 'm7071.77',
 'm7069.84',
 'm7067.91',
 'm7065.98',
 'm7064.05',
 'm7062.13',
 'm7060.2',
 'm7058.27',
 'm7056.34',
 'm7054.41',
 'm7052.48',
 'm7050.55',
 'm7048.63',
 'm7046.7',
 'm7044.77',
 'm7042.84',
 'm7040.91',
 'm7038.98',
 'm7037.06',
 'm7035.13',
 'm7033.2',
 'm7031.27',
 'm7029.34',
 'm7027.41',
 'm7025.48',
 'm7023.56',
 'm7021.63',
 'm7019.7',
 'm7017.77',
 'm7015.84',
 'm7013.91',
 'm7011.98',
 'm7010.06',
 'm7008.13',
 'm7006.2',
 'm7004.27',
 'm7002.34',
 'm7000.41',
 'm6998.49',
 'm6996.56',
 'm6994.63',
 'm6992.7',
 'm6990.77',
 'm6988.84',
 'm6986.91',
 'm6984.99',
 'm6983.06',
 'm6981.13',
 'm6979.2',
 'm6977.27',
 'm6975.34',
 'm6973.42',
 'm6971.49',
 'm6969.56',
 'm6967.63',
 'm6965.7',
 'm6963.77',
 'm6961.84',
 'm6959.92',
 'm6957.99',
 'm6956.06',
 'm6954.13',
 'm6952.2',
 'm6950.27',
 'm6948.34',
 'm6946.42',
 'm6944.49',
 'm6942.56',
 'm6940.63',
 'm6938.7',
 'm6936.77',
 'm6934.85',
 'm6932.92',
 'm6930.99',
 'm6929.06',
 'm6927.13',
 'm6925.2',
 'm6923.27',
 'm6921.35',
 'm6919.42',
 'm6917.49',
 'm6915.56',
 'm6913.63',
 'm6911.7',
 'm6909.77',
 'm6907.85',
 'm6905.92',
 'm6903.99',
 'm6902.06',
 'm6900.13',
 'm6898.2',
 'm6896.28',
 'm6894.35',
 'm6892.42',
 'm6890.49',
 'm6888.56',
 'm6886.63',
 'm6884.7',
 'm6882.78',
 'm6880.85',
 'm6878.92',
 'm6876.99',
 'm6875.06',
 'm6873.13',
 'm6871.21',
 'm6869.28',
 'm6867.35',
 'm6865.42',
 'm6863.49',
 'm6861.56',
 'm6859.63',
 'm6857.71',
 'm6855.78',
 'm6853.85',
 'm6851.92',
 'm6849.99',
 'm6848.06',
 'm6846.13',
 'm6844.21',
 'm6842.28',
 'm6840.35',
 'm6838.42',
 'm6836.49',
 'm6834.56',
 'm6832.64',
 'm6830.71',
 'm6828.78',
 'm6826.85',
 'm6824.92',
 'm6822.99',
 'm6821.06',
 'm6819.14',
 'm6817.21',
 'm6815.28',
 'm6813.35',
 'm6811.42',
 'm6809.49',
 'm6807.57',
 'm6805.64',
 'm6803.71',
 'm6801.78',
 'm6799.85',
 'm6797.92',
 'm6795.99',
 'm6794.07',
 'm6792.14',
 'm6790.21',
 'm6788.28',
 'm6786.35',
 'm6784.42',
 'm6782.49',
 'm6780.57',
 'm6778.64',
 'm6776.71',
 'm6774.78',
 'm6772.85',
 'm6770.92',
 'm6769',
 'm6767.07',
 'm6765.14',
 'm6763.21',
 'm6761.28',
 'm6759.35',
 'm6757.42',
 'm6755.5',
 'm6753.57',
 'm6751.64',
 'm6749.71',
 'm6747.78',
 'm6745.85',
 'm6743.92',
 'm6742',
 'm6740.07',
 'm6738.14',
 'm6736.21',
 'm6734.28',
 'm6732.35',
 'm6730.43',
 'm6728.5',
 'm6726.57',
 'm6724.64',
 'm6722.71',
 'm6720.78',
 'm6718.85',
 'm6716.93',
 'm6715',
 'm6713.07',
 'm6711.14',
 'm6709.21',
 'm6707.28',
 'm6705.36',
 'm6703.43',
 'm6701.5',
 'm6699.57',
 'm6697.64',
 'm6695.71',
 'm6693.78',
 'm6691.86',
 'm6689.93',
 'm6688',
 'm6686.07',
 'm6684.14',
 'm6682.21',
 'm6680.28',
 'm6678.36',
 'm6676.43',
 'm6674.5',
 'm6672.57',
 'm6670.64',
 'm6668.71',
 'm6666.79',
 'm6664.86',
 'm6662.93',
 'm6661',
 'm6659.07',
 'm6657.14',
 'm6655.21',
 'm6653.29',
 'm6651.36',
 'm6649.43',
 'm6647.5',
 'm6645.57',
 'm6643.64',
 'm6641.72',
 'm6639.79',
 'm6637.86',
 'm6635.93',
 'm6634',
 'm6632.07',
 'm6630.14',
 'm6628.22',
 'm6626.29',
 'm6624.36',
 'm6622.43',
 'm6620.5',
 'm6618.57',
 'm6616.64',
 'm6614.72',
 'm6612.79',
 'm6610.86',
 'm6608.93',
 'm6607',
 'm6605.07',
 'm6603.15',
 'm6601.22',
 'm6599.29',
 'm6597.36',
 'm6595.43',
 'm6593.5',
 'm6591.57',
 'm6589.65',
 'm6587.72',
 'm6585.79',
 'm6583.86',
 'm6581.93',
 'm6580',
 'm6578.07',
 'm6576.15',
 'm6574.22',
 'm6572.29',
 'm6570.36',
 'm6568.43',
 'm6566.5',
 'm6564.58',
 'm6562.65',
 'm6560.72',
 'm6558.79',
 'm6556.86',
 'm6554.93',
 'm6553',
 'm6551.08',
 'm6549.15',
 'm6547.22',
 'm6545.29',
 'm6543.36',
 'm6541.43',
 'm6539.51',
 'm6537.58',
 'm6535.65',
 'm6533.72',
 'm6531.79',
 'm6529.86',
 'm6527.93',
 'm6526.01',
 'm6524.08',
 'm6522.15',
 'm6520.22',
 'm6518.29',
 'm6516.36',
 'm6514.43',
 'm6512.51',
 'm6510.58',
 'm6508.65',
 'm6506.72',
 'm6504.79',
 'm6502.86',
 'm6500.94',
 'm6499.01',
 'm6497.08',
 'm6495.15',
 'm6493.22',
 'm6491.29',
 'm6489.36',
 'm6487.44',
 'm6485.51',
 'm6483.58',
 'm6481.65',
 'm6479.72',
 'm6477.79',
 'm6475.87',
 'm6473.94',
 'm6472.01',
 'm6470.08',
 'm6468.15',
 'm6466.22',
 'm6464.29',
 'm6462.37',
 'm6460.44',
 'm6458.51',
 'm6456.58',
 'm6454.65',
 'm6452.72',
 'm6450.79',
 'm6448.87',
 'm6446.94',
 'm6445.01',
 'm6443.08',
 'm6441.15',
 'm6439.22',
 'm6437.3',
 'm6435.37',
 'm6433.44',
 'm6431.51',
 'm6429.58',
 'm6427.65',
 'm6425.72',
 'm6423.8',
 'm6421.87',
 'm6419.94',
 'm6418.01',
 'm6416.08',
 'm6414.15',
 'm6412.22',
 'm6410.3',
 'm6408.37',
 'm6406.44',
 'm6404.51',
 'm6402.58',
 'm6400.65',
 'm6398.73',
 'm6396.8',
 'm6394.87',
 'm6392.94',
 'm6391.01',
 'm6389.08',
 'm6387.15',
 'm6385.23',
 'm6383.3',
 'm6381.37',
 'm6379.44',
 'm6377.51',
 'm6375.58',
 'm6373.66',
 'm6371.73',
 'm6369.8',
 'm6367.87',
 'm6365.94',
 'm6364.01',
 'm6362.08',
 'm6360.16',
 'm6358.23',
 'm6356.3',
 'm6354.37',
 'm6352.44',
 'm6350.51',
 'm6348.58',
 'm6346.66',
 'm6344.73',
 'm6342.8',
 'm6340.87',
 'm6338.94',
 'm6337.01',
 'm6335.09',
 'm6333.16',
 'm6331.23',
 'm6329.3',
 'm6327.37',
 'm6325.44',
 'm6323.51',
 'm6321.59',
 'm6319.66',
 'm6317.73',
 'm6315.8',
 'm6313.87',
 'm6311.94',
 'm6310.01',
 'm6308.09',
 'm6306.16',
 'm6304.23',
 'm6302.3',
 'm6300.37',
 'm6298.44',
 'm6296.52',
 'm6294.59',
 'm6292.66',
 'm6290.73',
 'm6288.8',
 'm6286.87',
 'm6284.94',
 'm6283.02',
 'm6281.09',
 'm6279.16',
 'm6277.23',
 'm6275.3',
 'm6273.37',
 'm6271.45',
 'm6269.52',
 'm6267.59',
 'm6265.66',
 'm6263.73',
 'm6261.8',
 'm6259.87',
 'm6257.95',
 'm6256.02',
 'm6254.09',
 'm6252.16',
 'm6250.23',
 'm6248.3',
 'm6246.37',
 'm6244.45',
 'm6242.52',
 'm6240.59',
 'm6238.66',
 'm6236.73',
 'm6234.8',
 'm6232.88',
 'm6230.95',
 'm6229.02',
 'm6227.09',
 'm6225.16',
 'm6223.23',
 'm6221.3',
 'm6219.38',
 'm6217.45',
 'm6215.52',
 'm6213.59',
 'm6211.66',
 'm6209.73',
 'm6207.81',
 'm6205.88',
 'm6203.95',
 'm6202.02',
 'm6200.09',
 'm6198.16',
 'm6196.23',
 'm6194.31',
 'm6192.38',
 'm6190.45',
 'm6188.52',
 'm6186.59',
 'm6184.66',
 'm6182.73',
 'm6180.81',
 'm6178.88',
 'm6176.95',
 'm6175.02',
 'm6173.09',
 'm6171.16',
 'm6169.24',
 'm6167.31',
 'm6165.38',
 'm6163.45',
 'm6161.52',
 'm6159.59',
 'm6157.66',
 'm6155.74',
 'm6153.81',
 'm6151.88',
 'm6149.95',
 'm6148.02',
 'm6146.09',
 'm6144.16',
 'm6142.24',
 'm6140.31',
 'm6138.38',
 'm6136.45',
 'm6134.52',
 'm6132.59',
 'm6130.67',
 'm6128.74',
 'm6126.81',
 'm6124.88',
 'm6122.95',
 'm6121.02',
 'm6119.09',
 'm6117.17',
 'm6115.24',
 'm6113.31',
 'm6111.38',
 'm6109.45',
 'm6107.52',
 'm6105.6',
 'm6103.67',
 'm6101.74',
 'm6099.81',
 'm6097.88',
 'm6095.95',
 'm6094.02',
 'm6092.1',
 'm6090.17',
 'm6088.24',
 'm6086.31',
 'm6084.38',
 'm6082.45',
 'm6080.52',
 'm6078.6',
 'm6076.67',
 'm6074.74',
 'm6072.81',
 'm6070.88',
 'm6068.95',
 'm6067.03',
 'm6065.1',
 'm6063.17',
 'm6061.24',
 'm6059.31',
 'm6057.38',
 'm6055.45',
 'm6053.53',
 'm6051.6',
 'm6049.67',
 'm6047.74',
 'm6045.81',
 'm6043.88',
 'm6041.96',
 'm6040.03',
 'm6038.1',
 'm6036.17',
 'm6034.24',
 'm6032.31',
 'm6030.38',
 'm6028.46',
 'm6026.53',
 'm6024.6',
 'm6022.67',
 'm6020.74',
 'm6018.81',
 'm6016.88',
 'm6014.96',
 'm6013.03',
 'm6011.1',
 'm6009.17',
 'm6007.24',
 'm6005.31',
 'm6003.39',
 'm6001.46',
 'm5999.53',
 'm5997.6',
 'm5995.67',
 'm5993.74',
 'm5991.81',
 'm5989.89',
 'm5987.96',
 'm5986.03',
 'm5984.1',
 'm5982.17',
 'm5980.24',
 'm5978.31',
 'm5976.39',
 'm5974.46',
 'm5972.53',
 'm5970.6',
 'm5968.67',
 'm5966.74',
 'm5964.82',
 'm5962.89',
 'm5960.96',
 'm5959.03',
 'm5957.1',
 'm5955.17',
 'm5953.24',
 'm5951.32',
 'm5949.39',
 'm5947.46',
 'm5945.53',
 'm5943.6',
 'm5941.67',
 'm5939.75',
 'm5937.82',
 'm5935.89',
 'm5933.96',
 'm5932.03',
 'm5930.1',
 'm5928.17',
 'm5926.25',
 'm5924.32',
 'm5922.39',
 'm5920.46',
 'm5918.53',
 'm5916.6',
 'm5914.67',
 'm5912.75',
 'm5910.82',
 'm5908.89',
 'm5906.96',
 'm5905.03',
 'm5903.1',
 'm5901.18',
 'm5899.25',
 'm5897.32',
 'm5895.39',
 'm5893.46',
 'm5891.53',
 'm5889.6',
 'm5887.68',
 'm5885.75',
 'm5883.82',
 'm5881.89',
 'm5879.96',
 'm5878.03',
 'm5876.11',
 'm5874.18',
 'm5872.25',
 'm5870.32',
 'm5868.39',
 'm5866.46',
 'm5864.53',
 'm5862.61',
 'm5860.68',
 'm5858.75',
 'm5856.82',
 'm5854.89',
 'm5852.96',
 'm5851.03',
 'm5849.11',
 'm5847.18',
 'm5845.25',
 'm5843.32',
 'm5841.39',
 'm5839.46',
 'm5837.54',
 'm5835.61',
 'm5833.68',
 'm5831.75',
 'm5829.82',
 'm5827.89',
 'm5825.96',
 'm5824.04',
 'm5822.11',
 'm5820.18',
 'm5818.25',
 'm5816.32',
 'm5814.39',
 'm5812.46',
 'm5810.54',
 'm5808.61',
 'm5806.68',
 'm5804.75',
 'm5802.82',
 'm5800.89',
 'm5798.97',
 'm5797.04',
 'm5795.11',
 'm5793.18',
 'm5791.25',
 'm5789.32',
 'm5787.39',
 'm5785.47',
 'm5783.54',
 'm5781.61',
 'm5779.68',
 'm5777.75',
 'm5775.82',
 'm5773.9',
 'm5771.97',
 'm5770.04',
 'm5768.11',
 'm5766.18',
 'm5764.25',
 'm5762.32',
 'm5760.4',
 'm5758.47',
 'm5756.54',
 'm5754.61',
 'm5752.68',
 'm5750.75',
 'm5748.82',
 'm5746.9',
 'm5744.97',
 'm5743.04',
 'm5741.11',
 'm5739.18',
 'm5737.25',
 'm5735.33',
 'm5733.4',
 'm5731.47',
 'm5729.54',
 'm5727.61',
 'm5725.68',
 'm5723.75',
 'm5721.83',
 'm5719.9',
 'm5717.97',
 'm5716.04',
 'm5714.11',
 'm5712.18',
 'm5710.25',
 'm5708.33',
 'm5706.4',
 'm5704.47',
 'm5702.54',
 'm5700.61',
 'm5698.68',
 'm5696.76',
 'm5694.83',
 'm5692.9',
 'm5690.97',
 'm5689.04',
 'm5687.11',
 'm5685.18',
 'm5683.26',
 'm5681.33',
 'm5679.4',
 'm5677.47',
 'm5675.54',
 'm5673.61',
 'm5671.69',
 'm5669.76',
 'm5667.83',
 'm5665.9',
 'm5663.97',
 'm5662.04',
 'm5660.11',
 'm5658.19',
 'm5656.26',
 'm5654.33',
 'm5652.4',
 'm5650.47',
 'm5648.54',
 'm5646.61',
 'm5644.69',
 'm5642.76',
 'm5640.83',
 'm5638.9',
 'm5636.97',
 'm5635.04',
 'm5633.12',
 'm5631.19',
 'm5629.26',
 'm5627.33',
 'm5625.4',
 'm5623.47',
 'm5621.54',
 'm5619.62',
 'm5617.69',
 'm5615.76',
 'm5613.83',
 'm5611.9',
 'm5609.97',
 'm5608.05',
 'm5606.12',
 'm5604.19',
 'm5602.26',
 'm5600.33',
 'm5598.4',
 'm5596.47',
 'm5594.55',
 'm5592.62',
 'm5590.69',
 'm5588.76',
 'm5586.83',
 'm5584.9',
 'm5582.97',
 'm5581.05',
 'm5579.12',
 'm5577.19',
 'm5575.26',
 'm5573.33',
 'm5571.4',
 'm5569.48',
 ...]

In [60]:
data_bez_korelacija =  data.drop(correlated_columns, axis=1)

In [61]:
data_bez_korelacija

,m7497.96,BSAN,BSAV,CTI,ELEV,EVI,LSTD,LSTN,REF2,REF3,RELI,TMAP,TMFI,Depth,Ca,P,pH,SOC,Sand
0,0.302553,-0.630435,-0.783875,-0.364146,1.165479,1.062682,-0.716713,-0.090016,-0.537106,-0.722567,1.687734,0.190708,0.056843,0,-0.295749,-0.041336,-1.129366,0.353258,1.269748
1,0.270192,-0.630435,-0.783875,-0.364146,1.165479,1.062682,-0.716713,-0.090016,-0.537106,-0.722567,1.687734,0.190708,0.056843,1,-0.387442,-0.231552,-1.531538,-0.264023,1.692209
2,0.317433,-0.753623,-0.929451,-0.633972,1.544098,1.156705,-1.282552,-0.088336,-0.631725,-0.832298,1.806660,0.190708,0.056843,0,-0.248601,-0.224635,-0.259551,0.064152,2.091835
3,0.261116,-0.753623,-0.929451,-0.633972,1.544098,1.156705,-1.282552,-0.088336,-0.631725,-0.832298,1.806660,0.190708,0.056843,1,-0.332195,-0.318014,-0.577548,-0.318719,2.118477
4,0.260038,-0.688406,-0.884658,-0.583576,1.276837,1.191691,-1.206971,0.011420,-0.528757,-0.795031,0.430513,0.190708,0.056843,0,-0.438350,-0.010210,-0.699135,-0.310905,2.164148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152,0.207530,-0.724638,-0.772676,0.038610,1.501782,0.306851,-0.511141,-0.481023,-0.940631,-0.966874,1.772681,1.539208,1.618022,0,-0.319468,-0.307638,-0.895545,3.056795,-0.971962
1153,0.182376,-0.724638,-0.772676,0.038610,1.501782,0.306851,-0.511141,-0.481023,-0.940631,-0.966874,1.772681,1.539208,1.618022,1,-0.309633,-0.380266,-0.727194,2.838012,-0.983380
1154,0.146829,-0.695652,-0.795073,-0.639966,1.287973,0.659621,-0.549317,-0.646528,-0.515770,-0.913043,2.944954,1.539208,1.618022,0,-0.446449,-0.380266,-0.409197,4.369495,-0.404874
1155,0.091910,-0.695652,-0.795073,-0.639966,1.287973,0.659621,-0.549317,-0.646528,-0.515770,-0.913043,2.944954,1.539208,1.618022,1,-0.493019,-0.418309,-0.194081,2.533278,-0.568530
1156,0.471388,-0.797101,-0.783875,0.087648,1.265702,0.271137,-0.245935,-0.444938,-0.914657,-0.956522,1.178050,1.539208,1.618022,0,-0.208974,-0.179675,-0.549490,3.970996,-0.420098

racunanje korelacije mi je ubilo operativni sistem

## Outlier-i

In [62]:
from scipy.stats import normaltest

norm = []
columns = data.select_dtypes(include='number').columns.tolist()
for column in columns:
    p = normaltest(data[column])
    if p.pvalue < 0.05:
        norm.append(False)
    else:
        norm.append(True)

print(pd.DataFrame(norm).sum(), data.shape)

0    418
dtype: int64 (1157, 3599)

Od 3599 kolona svega 418 ima normalnu raspodelu, pa ne mozemo koristiti z_score za uklanjanje outlier-a

In [63]:
data_numeric = data.select_dtypes(include='number')

data_bez_outliera = data

q1 = data_numeric.quantile(0.25)
q3 = data_numeric.quantile(0.75)
iqr = q3 - q1

columns = data_numeric.columns
for column in columns:
    if (column == 'Ca') | (column == 'P') | (column == 'pH') | (column == 'SOC') | (column == 'Sand'):
        continue
    data_bez_outliera = data_bez_outliera[(data_bez_outliera[column] >= q1[column] - 1.5 * iqr[column]) & (data_bez_outliera[column] <= q3[column] + 1.5 * iqr[column])]

In [64]:
data_bez_outliera.shape

(715, 3599)

Izbacivanjem outliera izgubili smo preveliku kolicinu podataka, pa cemo ih clippovati

In [65]:
data_numeric = data.select_dtypes(include='number')

data_clipped = data

q1 = data_numeric.quantile(0.25)
q3 = data_numeric.quantile(0.75)
iqr = q3 - q1

columns = data_numeric.columns
for column in columns:
    if (column == 'Ca') | (column == 'P') | (column == 'pH') | (column == 'SOC') | (column == 'Sand'):
        continue
    min = q1[column] - 1.5 * iqr[column]
    max = q3[column] + 1.5 * iqr[column]
    data_clipped[column] = data_clipped[column].clip(upper=max, lower=min)

## Modeli

Linearna regresija

In [66]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

model_lin_reg = LinearRegression(n_jobs=-1)
pipeline_lin_reg = Pipeline([
    ('scaler', StandardScaler()),
    ('model_lin_reg', model_lin_reg),
])
grid_params = {
    'scaler' : [None, StandardScaler()],
    'model_lin_reg__fit_intercept' : [False, True],
}

grid_lin_reg = GridSearchCV(pipeline_lin_reg, grid_params, n_jobs=-1, cv=5, scoring='neg_mean_squared_error')

Klasifikaciono stablo

In [67]:
from sklearn.tree import DecisionTreeRegressor

model_tree = DecisionTreeRegressor(random_state=7)
pipeline_tree = Pipeline([
    #('scaler', StandardScaler()),
    ('model_tree', model_tree),
])

parameters_tree = {
    "model_tree__ccp_alpha" : [0.0, 0.05, 0.0025],
    "model_tree__max_depth" : [2, 5, 7, 9, 11],
    "model_tree__criterion" : ['squared_error', 'friedman_mse', 'absolute_error'],
}

grid_tree = GridSearchCV(pipeline_tree, parameters_tree, n_jobs=-1, cv=5, scoring='neg_mean_squared_error')

## Sa outlierima

Izdvajamo izlazna obelezja

In [68]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error

def the_funkcija(grid, trening_set, validacija_set, output_name):
    # izdvajanje izlaznih obelezja
    y_Ca = trening_set['Ca']
    y_P  = trening_set['P']
    y_pH = trening_set['pH']
    y_SOC = trening_set['SOC']
    y_Sand = trening_set['Sand']
    X = trening_set.drop(['Ca', 'P', 'pH', 'SOC', 'Sand'], axis=1)
    # train test split
    X_train_Ca, X_test_Ca, y_train_Ca, y_test_Ca = train_test_split(X, y_Ca, test_size=0.2, random_state=7)
    X_train_P, X_test_P, y_train_P, y_test_P = train_test_split(X, y_P, test_size=0.2, random_state=7)
    X_train_pH, X_test_pH, y_train_pH, y_test_pH = train_test_split(X, y_pH, test_size=0.2, random_state=7)
    X_train_SOC, X_test_SOC, y_train_SOC, y_test_SOC = train_test_split(X, y_SOC, test_size=0.2, random_state=7)
    X_train_Sand, X_test_Sand, y_train_Sand, y_test_Sand = train_test_split(X, y_Sand, test_size=0.2, random_state=7)
    # krosvalidacija
    grid_Ca = grid.fit(X_train_Ca, y_train_Ca)
    best_model_Ca = grid_Ca.best_estimator_
    best_params_Ca = grid_Ca.best_params_

    grid_P = grid.fit(X_train_P, y_train_P)
    best_model_P = grid_P.best_estimator_
    best_params_P = grid_P.best_params_

    grid_pH = grid.fit(X_train_pH, y_train_pH)
    best_model_pH = grid_pH.best_estimator_
    best_params_pH = grid_pH.best_params_

    grid_SOC = grid.fit(X_train_SOC, y_train_SOC)
    best_model_SOC = grid_SOC.best_estimator_
    best_params_SOC = grid_SOC.best_params_

    grid_Sand = grid.fit(X_train_Sand, y_train_Sand)
    best_model_Sand = grid_Sand.best_estimator_
    best_params_Sand = grid_Sand.best_params_

    # kalkulacija rmse
    y_RMSE_Ca = root_mean_squared_error(best_model_Ca.predict(X_test_Ca), y_test_Ca)
    y_RMSE_P = root_mean_squared_error(best_model_P.predict(X_test_P), y_test_P)
    y_RMSE_pH = root_mean_squared_error(best_model_pH.predict(X_test_pH), y_test_pH)
    y_RMSE_SOC = root_mean_squared_error(best_model_SOC.predict(X_test_SOC), y_test_SOC)
    y_RMSE_Sand = root_mean_squared_error(best_model_Sand.predict(X_test_Sand), y_test_Sand)

    # validacija
    prediction = pd.DataFrame()
    prediction['PIDN'] = validacija_set['PIDN']
    validacija_set.drop('PIDN', inplace=True, axis=1)

    prediction['Ca'] = pd.DataFrame(best_model_Ca.set_params(**best_params_Ca).fit(X, y_Ca).predict(validacija_set))
    prediction['P'] = pd.DataFrame(best_model_P.set_params(**best_params_P).fit(X, y_P).predict(validacija_set))
    prediction['pH'] = pd.DataFrame(best_model_pH.set_params(**best_params_pH).fit(X, y_pH).predict(validacija_set))
    prediction['SOC'] = pd.DataFrame(best_model_SOC.set_params(**best_params_SOC).fit(X, y_SOC).predict(validacija_set))
    prediction['Sand'] = pd.DataFrame(best_model_Sand.set_params(**best_params_Sand).fit(X, y_Sand).predict(validacija_set))

    prediction.to_csv("predictions/" + output_name + ".csv", index=False)

    return {
        "Ca" : y_RMSE_Ca,
        "P" : y_RMSE_P,
        "pH": y_RMSE_pH,
        "SOC": y_RMSE_SOC,
        "Sand": y_RMSE_Sand,
        "MCRMSE" : (y_RMSE_Ca + y_RMSE_P + y_RMSE_pH + y_RMSE_SOC + y_RMSE_Sand)/5,
    }

In [69]:
sorted_test = pd.read_csv('data/sorted_test.csv')
test_lin_reg = sorted_test.copy()
test_lin_reg['Depth'] = test_lin_reg['Depth'].replace({'Topsoil' : 0 , 'Subsoil' : 1})

In [70]:
print(the_funkcija(grid_lin_reg, data, test_lin_reg, "lin_reg"))

{'Ca': 0.5049645752975458, 'P': 1.6576700943521183, 'pH': 0.7543211407602292, 'SOC': 0.7051158437573091, 'Sand': 0.7294245874734764, 'MCRMSE': 0.8702992483281358}

In [71]:
test_tree = sorted_test.copy()
test_tree['Depth'] = test_tree['Depth'].replace({'Topsoil' : 0 , 'Subsoil' : 1})

In [72]:
print(the_funkcija(grid_tree, data, test_tree, "tree"))

{'Ca': 0.5648514501553454, 'P': 1.0588995128583363, 'pH': 0.6745977967977185, 'SOC': 0.5302018230051582, 'Sand': 0.5241819155477588, 'MCRMSE': 0.6705464996728635}

## Bez outliera

In [73]:
test_lin_reg_c = sorted_test.copy()
test_lin_reg_c['Depth'] = test_lin_reg_c['Depth'].replace({'Topsoil' : 0 , 'Subsoil' : 1})

In [74]:
print(the_funkcija(grid_lin_reg, data_clipped, test_lin_reg_c, "lin_reg_clipped"))

{'Ca': 0.5049645752975458, 'P': 1.6576700943521183, 'pH': 0.7543211407602292, 'SOC': 0.7051158437573091, 'Sand': 0.7294245874734764, 'MCRMSE': 0.8702992483281358}

In [75]:
test_tree_clipped = sorted_test.copy()
test_tree_clipped['Depth'] = test_tree_clipped['Depth'].replace({'Topsoil' : 0 , 'Subsoil' : 1})

In [76]:
print(the_funkcija(grid_tree, data_clipped, test_tree_clipped, "tree_clipped"))

{'Ca': 0.5648514501553454, 'P': 1.0588995128583363, 'pH': 0.6745977967977185, 'SOC': 0.5302018230051582, 'Sand': 0.5241819155477588, 'MCRMSE': 0.6705464996728635}

Zakljucujemo da linearna regresija trenirana na clippovanim podacima radi isto

## Bez korelisanih kolona

In [77]:
test_lin_reg_bk = sorted_test.copy()
test_lin_reg_bk['Depth'] = test_lin_reg_bk['Depth'].replace({'Topsoil' : 0 , 'Subsoil' : 1})
test_lin_reg_bk = test_lin_reg_bk.drop(correlated_columns, axis=1)

In [78]:
print(the_funkcija(grid_lin_reg, data_bez_korelacija, test_lin_reg_bk, "lin_reg_bez_korelacija"))

{'Ca': 0.8329978812820192, 'P': 0.6988197190977719, 'pH': 0.6801143967048152, 'SOC': 0.8315303328421029, 'Sand': 0.7703700255047135, 'MCRMSE': 0.7627664710862845}

In [79]:
test_tree_bk = sorted_test.copy()
test_tree_bk['Depth'] = test_tree_bk['Depth'].replace({'Topsoil' : 0 , 'Subsoil' : 1})
test_tree_bk = test_tree_bk.drop(correlated_columns, axis=1)

In [80]:
print(the_funkcija(grid_tree, data_bez_korelacija, test_tree_bk, "tree_bez_korelacija"))

{'Ca': 0.5108288448240199, 'P': 0.7250483854005842, 'pH': 0.6163802595768648, 'SOC': 0.722614972588117, 'Sand': 0.5259174484953628, 'MCRMSE': 0.6201579821769898}

## Polynomial features

broj polinoma je prevelik pre izbacivanja korelisanih kolona, pa samo ovde koristimo polynomial features

ostavili smo samo drugi stepen polinoma jer visi stepeni daju isti rezulatat

In [81]:
from sklearn.preprocessing import PolynomialFeatures

pipeline_lin_reg_polynomial = Pipeline([
    ('scaler', StandardScaler()),
    ('feature_generator', PolynomialFeatures()),
    ('model_lin_reg', model_lin_reg),
])
grid_params = {
    'scaler' : [None, StandardScaler()],
    'feature_generator' : [None, PolynomialFeatures(degree=2)],
    'model_lin_reg__fit_intercept' : [False, True],
}

grid_lin_reg_polynomial = GridSearchCV(pipeline_lin_reg_polynomial, grid_params, n_jobs=-1, cv=5, scoring='neg_mean_squared_error')

In [82]:
test_lin_reg_bk_pol = sorted_test.copy()
test_lin_reg_bk_pol['Depth'] = test_lin_reg_bk_pol['Depth'].replace({'Topsoil' : 0 , 'Subsoil' : 1})
test_lin_reg_bk_pol = test_lin_reg_bk_pol.drop(correlated_columns, axis=1)

In [83]:
print(the_funkcija(grid_lin_reg_polynomial, data_bez_korelacija, test_lin_reg_bk_pol, "lin_reg_bez_korelacija_polynomial"))

{'Ca': 0.6420833025861913, 'P': 0.6988197190977719, 'pH': 0.6189733116872884, 'SOC': 0.766177253697109, 'Sand': 0.6706059297434439, 'MCRMSE': 0.6793319033623609}

In [84]:

pipeline_tree_polynomial = Pipeline([
    #('scaler', StandardScaler()),
    ('feature_generator', 'passthrough'),
    ('model_tree', model_tree),
])

parameters_tree = {
    "model_tree__ccp_alpha" : [0.0, 0.05, 0.0025],
    "model_tree__max_depth" : [2, 5, 7, 9, 11],
    "model_tree__criterion" : ['squared_error', 'friedman_mse', 'absolute_error'],
    "feature_generator" : ['passthrough', PolynomialFeatures(degree=2)]
}

grid_tree_polynomial = GridSearchCV(pipeline_tree_polynomial, parameters_tree, n_jobs=-1, cv=5, scoring='neg_mean_squared_error')

In [85]:
test_tree_bk_pol = sorted_test.copy()
test_tree_bk_pol['Depth'] = test_tree_bk_pol['Depth'].replace({'Topsoil' : 0 , 'Subsoil' : 1})
test_tree_bk_pol = test_tree_bk_pol.drop(correlated_columns, axis=1)

In [86]:
print(the_funkcija(grid_tree_polynomial, data_bez_korelacija, test_tree_bk_pol, "tree_bez_korelacija_polynomial"))

{'Ca': 0.5108288448240199, 'P': 0.7250483854005842, 'pH': 0.6163802595768648, 'SOC': 0.722614972588117, 'Sand': 0.5259174484953628, 'MCRMSE': 0.6201579821769898}